GET http://localhost:3000/api/games
Content-Type: application/json

###

GET http://localhost:3000/api/game/fa07c93b-0af4-4b84-852f-0bc723235d42
Content-Type: application/json

###

POST http://localhost:3000/api/game
Content-Type: application/json

{
  "title": "New Game 2",
  "genres": [ "action", "adventure" ],
  "price": 40
}

###

DELETE http://localhost:3000/api/game/2
Content-Type: application/json

###

PUT http://localhost:3000/api/game/2
Content-Type: application/json

{
  "title": "Game Updated",
  "genre": [ "rpg" ],
  "price": 30
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
  "email": "herlon@mail.com",
  "password": "herlon"
}
